org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.0.1-SNAPSHOT
maven_group = net.tvoid.lib
archives_name = tvoidlib
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.3

# Dependencies
architectury_api_version = 22.0.2
fabric_loader_version = 0.19.5
fabric_api_version = 0.160.5+26.3
neoforge_version = 26.3.0.1-beta