modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = ""

[[mods]]
modId = "tvoidlib"
version = "${version}"
displayName = "tvoid lib"
authors = "tvoid"
description = '''
Multiplatform modding library. You know how this goes...
'''
#logoFile = ""

[[dependencies.tvoidlib]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tvoidlib]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tvoidlib]]
modId = "architectury"
type = "required"
versionRange = "[22.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tvoidlib.mixins.json"